### ISSUE TITLE
Network connection lost issue in IOS

### ISSUE THREAD

**Issue by kittu4ios** [paypal/sdk-packages#101] opened 2017-01-10 08:10 UTC
HI I just downloaded app and run the application. I got below issue. 
InteractiveDemo[8696:473141] Checking Error********************
2017-01-10 13:39:09.796 InteractiveDemo[8696:473141] Posting Error: -1

can you please tell me how to fix this issue,

**Comment by kittu4ios** [comment] 2017-01-18 07:01
HI, Still I am facing same problem. But now i am getting alert while app launching "system unavailable, please try again later alert" at initialize time.

**Comment by bluk** [comment] 2017-01-18 16:11
Sorry for the delay in response. I've opened internal issue PPPLMER-25614 to track down the "System is unavailable. Please try again later." alert in the sandbox environment. I will close this as a duplicate of #98 since it seems to be the same issue and you've commented on it there.

**Closed by bluk** 2017-01-18 16:11 UTC
